dataset:
  batch_size: 20
  corpus:
    dev_path: dev.conllu
    root: /home/amysiak/thesis/multilingual-probing-visualization/data/conllu
    test_path: test.conllu
    train_path: train.conllu
  embeddings:
    dev_path: dev.hdf5
    root: /home/amysiak/thesis/multilingual-probing-visualization/data/hdf5
    test_path: test.hdf5
    train_path: train.hdf5
    type: token
  keys:
    dev:
    - id
    test:
    - id
    train:
    - pl
  limit: null
  observation_fieldnames:
  - index
  - sentence
  - lemma_sentence
  - upos_sentence
  - xpos_sentence
  - morph
  - head_indices
  - governance_relations
  - secondary_relations
  - extra_info
  - langs
  - embeddings
model:
  hidden_dim: 768
  model_layer: 6
  model_type: BERT-disk
  multilingual: true
  use_disk: true
probe:
  diagonal: false
  maximum_rank: 128
  params_path: predictor.params
  psd_parameters: true
  task_name: parse-distance
  task_signature: word_pair
probe_training:
  epochs: 30
  loss: L1
reporting:
  observation_paths:
    dev_path: dev.observations
    test_path: test.observations
    train_path: train.observations
  prediction_paths:
    dev_path: dev.predictions
    test_path: test.predictions
    train_path: train.predictions
  reporting_methods:
  - spearmanr
  - uuas
  - proj_acc
  - adj_acc
  root: /home/amysiak/thesis/multilingual-probing-visualization/probingOutputs/all_slavic
